[package]
name = "nerd-fonts-cheat-sheet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Nerd Fonts cheat sheet application"
publish = true

[features]
default = ["gtk", "embed-fonts", "metadata"]

gtk = ["nerd-fonts-rs/gtk"]
embed-fonts = ["nerd-fonts-rs/embed-fonts"]
metadata = ["nerd-fonts-rs/metadata"]

[dependencies]
nerd-fonts-model.workspace = true
nerd-fonts-rs.workspace = true
gtk4 = { workspace = true, features = ["v4_12"] }
miette.workspace = true

[lints]
workspace = true
