// build.rs: export Bravura glyphs and generate codepoint maps + constants.
//
// Bravura is a SMuFL-compliant OpenType music font with ~2600+ glyphs
// covering conventional music notation symbols. All glyphs are mapped
// to the Unicode Private Use Area (U+E000–U+F8FF) per the SMuFL spec.
//
// The Bravura OTF uses a post table version 3.0 (no PostScript glyph
// names), so glyph names come from the SMuFL specification's
// glyphnames.json metadata file instead of the font itself.

use std::collections::HashMap;
use std::path::Path;
use std::str::FromStr;

use fonts_rs_generator::ExportConfig;
use fonts_rs_generator::FontBuild;
use fonts_rs_generator::build_constants;
use fonts_rs_generator::export_glyphs_by_name_map;
use fonts_rs_model::CodePoint;
use fonts_rs_model::GRESOURCE_BASE_PREFIX;
use fonts_rs_model::GlyphNameMap;
use fonts_rs_model::PUA_RANGE;
use miette::IntoDiagnostic;
use serde::Deserialize;

/// OTF font file name (relative to `resources/`).
pub const FONT_FILE: &str = "Bravura.otf";

/// SMuFL glyphnames.json file name (relative to `resources/`).
pub const GLYPHNAMES_FILE: &str = "glyphnames.json";

/// Deserialization struct for a glyphnames.json entry.
#[derive(Deserialize)]
struct GlyphNameEntry {
    codepoint: String,
}

/// Parse SMuFL glyphnames.json into a HashMap of glyph name -> codepoint.
///
/// The JSON format is: `{ "glyphName": { "codepoint": "U+E050", "description": "..." } }`
fn parse_glyphnames(json: &str) -> miette::Result<GlyphNameMap> {
    let entries: HashMap<String, GlyphNameEntry> = serde_json::from_str(json).map_err(|e| miette::miette!("Failed to parse glyphnames.json: {e}"))?;

    let mut map = GlyphNameMap::new();
    for (name, entry) in entries {
        let cp = CodePoint::from_str(&entry.codepoint).map_err(|e| miette::miette!("Failed to parse codepoint {}: {e}", entry.codepoint))?;
        map.insert(name, cp);
    }
    Ok(map)
}

fn main() -> miette::Result<()> {
    let font_path = format!("{}/{}", build_constants::RESOURCES_DIR, FONT_FILE);
    let glyphnames_path = format!("{}/{}", build_constants::RESOURCES_DIR, GLYPHNAMES_FILE);

    eprintln!("build.rs: exporting glyphs from {font_path}");

    // Set env var with absolute path so include_bytes! in fonts.rs can find it.
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| std::env::current_dir().unwrap().to_string_lossy().to_string());
    let absolute_font_path = Path::new(&crate_dir).join(&font_path);
    println!("cargo:rustc-env=BRAVURA_FONT_PATH={}", absolute_font_path.display());

    // Parse SMuFL glyph names
    let glyphnames_json = std::fs::read_to_string(&glyphnames_path).map_err(|e| miette::miette!("Failed to read {glyphnames_path}: {e}"))?;
    let name_map = parse_glyphnames(&glyphnames_json)?;
    eprintln!("build.rs: parsed {} SMuFL glyph names", name_map.len());

    let glyph_prefix = "bravura";
    let gresource_prefix = format!("{}/bravura", GRESOURCE_BASE_PREFIX);

    let config = ExportConfig {
        gresource_prefix: gresource_prefix.clone(),
        icons_context: "glyphs".to_string(),
        glyph_name_prefix: glyph_prefix.to_string(),
        codepoint_ranges: &[PUA_RANGE],
        axes: vec![],
        name_filter: None,
    };

    let icons_dir = Path::new(build_constants::RESOURCES_DIR).join("scalable").join("glyphs");

    FontBuild::new(&font_path)
        .run(|font_path, resources_dir| {
            if icons_dir.exists() {
                std::fs::remove_dir_all(&icons_dir)?;
            }
            export_glyphs_by_name_map(font_path, resources_dir, &config, &name_map)
        })
        .map_err(|e| miette::miette!("{e}"))?;

    // Generate variant info for runtime use.
    let out_dir = std::env::var("OUT_DIR").into_diagnostic()?;
    let variant_info = format!(
        "// @generated by build.rs — do not edit\n\n\
         /// GResource prefix for Bravura.\n\
         pub const GRESOURCE_PREFIX: &str = \"{gresource_prefix}\";\n\n\
         /// Glyph name prefix for Bravura.\n\
         pub const GLYPH_PREFIX: &str = \"{glyph_prefix}\";\n"
    );
    std::fs::write(Path::new(&out_dir).join("variant.rs"), variant_info).into_diagnostic()?;

    Ok(())
}
