[package]
name = "nerd-fonts-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Build-time code generation and icon export for Nerd Fonts"
publish = true

[dependencies]
nerd-fonts-model.workspace = true
fonts-rs-model.workspace = true
fonts-rs-generator.workspace = true
skrifa.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
clap.workspace = true
miette.workspace = true
thiserror.workspace = true

[[bin]]
name = "export_icons"
path = "src/bin/export_icons.rs"

[[example]]
name = "generate_nerd_fonts"

[lints]
workspace = true
