//! Generator for phf::Map codepoint lookup tables.

use super::error::GenerateError;
use super::generate::GlyphGenerator;
use fonts_rs_model::GlyphEntry;
use serde::Deserialize;
use serde::Serialize;
use std::path::PathBuf;

/// Generates phf::Map constants for both codepoint-to-name and name-to-codepoint lookups.
pub struct CodemapGenerator;

impl<N> GlyphGenerator<N> for CodemapGenerator
where
    N: AsRef<str> + Clone + Ord + Serialize + for<'a> Deserialize<'a>,
{
    fn generate(entries: &[GlyphEntry<N>]) -> Result<String, GenerateError> {
        let mut output = String::new();
        output.push_str("// @generated by build.rs — do not edit\n\n");
        output.push_str("use phf::phf_map;\n\n");

        // Codepoint -> name map
        output.push_str("pub static GLYPHS: phf::Map<char, &'static str> = phf_map! {\n");
        for entry in entries {
            let Some(code) = &entry.code else { continue };
            let ch = code.as_char();
            output.push_str(&format!("    '\\u{{{:X}}}' => \"{}\",\n", ch as u32, entry.name.as_ref()));
        }
        output.push_str("};\n\n");

        // Name -> codepoint map (reverse lookup)
        output.push_str("pub static REVERSE_GLYPHS: phf::Map<&'static str, char> = phf_map! {\n");
        for entry in entries {
            let Some(code) = &entry.code else { continue };
            let ch = code.as_char();
            output.push_str(&format!("    \"{}\" => '\\u{{{:X}}}',\n", entry.name.as_ref(), ch as u32));
        }
        output.push_str("};\n");

        Ok(output)
    }

    fn output_path() -> Result<PathBuf, GenerateError> {
        let out_dir = std::env::var("OUT_DIR")?;
        Ok(PathBuf::from(out_dir).join("codemap.rs"))
    }
}
