//! Generic metadata generator trait for build-time phf::Map code generation.
//!
//! Provides [`MetadataGenerator`] — a trait for generating `phf::Map` constants
//! for keywords, categories, and aliases from glyph metadata. Each font family
//! implements the data-source methods (`keywords_for`, `categories_for`,
//! `aliases`); the code-generation methods (`generate_keywords`,
//! `generate_categories`, `generate_aliases`, `run`) are provided by default.
//!
//! The [`MetadataGenerator::deduplicate_statics`] hook controls whether
//! generated `phf::Map` entries reference shared `static` constants (for large
//! maps with many duplicate value lists) or inline the values directly.

use std::collections::HashMap;
use std::path::PathBuf;

use fonts_rs_model::GlyphEntry;

/// Escapes a string for use in a Rust string literal.
pub fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Trait for generating `phf::Map` metadata tables from glyph entries.
///
/// Each font family implements the data-source methods to provide keywords,
/// categories, and aliases. The code-generation methods have default
/// implementations that produce `phf::Map` Rust source code.
///
/// # Code Generation Modes
///
/// When [`MetadataGenerator::deduplicate_statics`] returns `true`, the
/// generated code extracts repeated value lists into `static` constants
/// (e.g. `static KW_0: &[GlyphKeyword] = &[...]`) and references them from
/// the `phf::Map`. This reduces binary size for large maps with many
/// duplicate keyword or category lists.
///
/// When it returns `false` (the default), values are inlined directly in
/// the `phf::Map` entries.
pub trait MetadataGenerator {
    /// The glyph name type (e.g. `String` for noto-emoji, `IconName` for nerd-fonts).
    type Name: AsRef<str>;

    /// Returns keywords for the given glyph entry, or an empty vec if none.
    fn keywords_for(&self, entry: &GlyphEntry<Self::Name>) -> Vec<String>;

    /// Returns categories for the given glyph entry, or an empty vec if none.
    fn categories_for(&self, entry: &GlyphEntry<Self::Name>) -> Vec<String>;

    /// Returns all aliases as `(alias, canonical)` pairs.
    ///
    /// Default implementation returns an empty vec (no aliases).
    fn aliases(&self) -> Vec<(String, String)> {
        Vec::new()
    }

    /// Whether to extract repeated value lists into `static` constants.
    ///
    /// Override to return `true` for large maps with many duplicate value
    /// lists (e.g. nerd-fonts with thousands of icons sharing categories).
    /// Default is `false` (inline values directly).
    fn deduplicate_statics() -> bool {
        false
    }

    /// Generates the keywords `phf::Map` content as Rust source code.
    fn generate_keywords(&self, entries: &[GlyphEntry<Self::Name>]) -> String {
        let mut output = String::new();
        output.push_str("// @generated by build.rs — do not edit\n\n");

        if Self::deduplicate_statics() {
            let mut kw_idx = 0usize;
            let mut kw_entries = Vec::new();

            for entry in entries {
                let keywords = self.keywords_for(entry);
                if keywords.is_empty() {
                    continue;
                }

                let static_name = format!("KW_{}", kw_idx);
                output.push_str(&format!("static {}: &[GlyphKeyword] = &[", static_name));
                for (i, kw) in keywords.iter().enumerate() {
                    if i > 0 {
                        output.push_str(", ");
                    }
                    output.push_str(&format!("GlyphKeyword::new(\"{}\")", escape_str(kw)));
                }
                output.push_str("];\n");
                kw_entries.push((entry.name.as_ref().to_string(), static_name));
                kw_idx += 1;
            }

            output.push_str("\npub static KEYWORDS: GlyphKeywordMap = GlyphKeywordMap(phf::phf_map! {\n");
            for (name, static_name) in &kw_entries {
                output.push_str(&format!("    \"{}\" => {},\n", escape_str(name), static_name));
            }
            output.push_str("});\n");
        } else {
            output.push_str("pub static KEYWORDS: GlyphKeywordMap = GlyphKeywordMap(phf::phf_map! {\n");
            for entry in entries {
                let keywords = self.keywords_for(entry);
                if keywords.is_empty() {
                    continue;
                }
                let kw_refs: Vec<String> = keywords.iter().map(|k| format!("GlyphKeyword::new(\"{}\")", escape_str(k))).collect();
                output.push_str(&format!("    \"{}\" => &[{}],\n", escape_str(entry.name.as_ref()), kw_refs.join(", ")));
            }
            output.push_str("});\n");
        }

        output
    }

    /// Generates the categories `phf::Map` content as Rust source code.
    fn generate_categories(&self, entries: &[GlyphEntry<Self::Name>]) -> String {
        let mut output = String::new();
        output.push_str("// @generated by build.rs — do not edit\n\n");

        if Self::deduplicate_statics() {
            let mut cat_to_static: HashMap<String, String> = HashMap::new();
            let mut cat_idx = 0usize;
            let mut cat_entries = Vec::new();

            for entry in entries {
                let categories = self.categories_for(entry);
                if categories.is_empty() {
                    continue;
                }

                let key = categories.join("\0");
                let static_name = cat_to_static
                    .entry(key)
                    .or_insert_with(|| {
                        let name = format!("CAT_{}", cat_idx);
                        cat_idx += 1;
                        output.push_str(&format!("static {}: &[GlyphCategory] = &[", name));
                        for (i, cat) in categories.iter().enumerate() {
                            if i > 0 {
                                output.push_str(", ");
                            }
                            output.push_str(&format!("GlyphCategory::new(\"{}\")", escape_str(cat)));
                        }
                        output.push_str("];\n");
                        name
                    })
                    .clone();
                cat_entries.push((entry.name.as_ref().to_string(), static_name));
            }

            output.push_str("\npub static CATEGORIES: GlyphCategoryMap = GlyphCategoryMap(phf::phf_map! {\n");
            for (name, static_name) in &cat_entries {
                output.push_str(&format!("    \"{}\" => {},\n", escape_str(name), static_name));
            }
            output.push_str("});\n");
        } else {
            output.push_str("pub static CATEGORIES: GlyphCategoryMap = GlyphCategoryMap(phf::phf_map! {\n");
            for entry in entries {
                let categories = self.categories_for(entry);
                if categories.is_empty() {
                    continue;
                }
                let cat_refs: Vec<String> = categories.iter().map(|c| format!("GlyphCategory::new(\"{}\")", escape_str(c))).collect();
                output.push_str(&format!("    \"{}\" => &[{}],\n", escape_str(entry.name.as_ref()), cat_refs.join(", ")));
            }
            output.push_str("});\n");
        }

        output
    }

    /// Generates the aliases `phf::Map` content as Rust source code.
    fn generate_aliases(&self) -> String {
        let mut output = String::new();
        output.push_str("// @generated by build.rs — do not edit\n\n");

        let alias_entries = self.aliases();

        output.push_str("pub static ALIASES: GlyphAliasMap = GlyphAliasMap(phf::phf_map! {\n");
        for (alias, canonical) in &alias_entries {
            output.push_str(&format!("    \"{}\" => \"{}\",\n", escape_str(alias), escape_str(canonical)));
        }
        output.push_str("});\n");

        output
    }

    /// Writes the generated metadata to separate files in `OUT_DIR`.
    ///
    /// Produces `keywords.rs`, `categories.rs`, and `aliases.rs`.
    fn run(&self, entries: &[GlyphEntry<Self::Name>]) -> Result<(), std::io::Error> {
        let out_dir = std::env::var("OUT_DIR").map_err(|e| std::io::Error::other(format!("OUT_DIR not set: {e}")))?;
        let out_dir = PathBuf::from(out_dir);
        std::fs::create_dir_all(&out_dir)?;

        let keywords = self.generate_keywords(entries);
        std::fs::write(out_dir.join("keywords.rs"), keywords)?;

        let categories = self.generate_categories(entries);
        std::fs::write(out_dir.join("categories.rs"), categories)?;

        let aliases = self.generate_aliases();
        std::fs::write(out_dir.join("aliases.rs"), aliases)?;

        Ok(())
    }
}
