//! Generator for Rust glyph name constants.

use super::error::GenerateError;
use super::generate::GlyphGenerator;
use fonts_rs_model::GlyphEntry;
use serde::Deserialize;
use serde::Serialize;
use std::collections::HashSet;
use std::path::PathBuf;

/// Generates Rust constants for each glyph name.
pub struct RustConstantsGenerator;

impl<N> GlyphGenerator<N> for RustConstantsGenerator
where
    N: AsRef<str> + Clone + Ord + Serialize + for<'a> Deserialize<'a>,
{
    fn generate(entries: &[GlyphEntry<N>]) -> Result<String, GenerateError> {
        let names: HashSet<String> = entries.iter().map(|entry| entry.name.as_ref().to_string()).collect();

        let mut output = String::new();
        output.push_str("// @generated by build.rs — do not edit\n\n");

        for name in names {
            let const_name = name.to_uppercase().replace('-', "_");
            output.push_str(&format!("pub const {}: &str = \"{}\";\n", const_name, name));
        }

        Ok(output)
    }

    fn output_path() -> Result<PathBuf, GenerateError> {
        let out_dir = std::env::var("OUT_DIR")?;
        Ok(PathBuf::from(out_dir).join("icons.rs"))
    }
}
