// build.rs: export Redacted glyphs and generate codepoint maps + constants.
//
// The Redacted font family has two sub-families:
// - Redacted (block bars): single static Regular instance
// - RedactedScript (scribble): Light, Regular, Bold
//
// This build script selects one variant based on the active Cargo feature
// and exports glyphs from the corresponding TTF file.

use std::path::Path;

use fonts_rs_generator::ExportConfig;
use fonts_rs_generator::FontBuild;
use fonts_rs_generator::build_constants;
use fonts_rs_generator::export_glyphs_with_config;
use fonts_rs_model::GRESOURCE_BASE_PREFIX;
use miette::IntoDiagnostic;

/// All Redacted variants and their mapping to TTF filenames.
const VARIANTS: &[(&str, &str)] = &[
    ("redacted", "Redacted-Regular"),
    ("script-light", "RedactedScript-Light"),
    ("script-regular", "RedactedScript-Regular"),
    ("script-bold", "RedactedScript-Bold"),
];

fn main() -> miette::Result<()> {
    let active = VARIANTS
        .iter()
        .filter(|(feat, _)| std::env::var(format!("CARGO_FEATURE_{}", feat.replace('-', "_").to_uppercase())).is_ok())
        .collect::<Vec<_>>();

    if active.is_empty() {
        eprintln!("build.rs: no Redacted variant feature active, defaulting to redacted");
    } else if active.len() > 1 {
        eprintln!("build.rs: expected at most one Redacted variant feature, found {active_len}", active_len = active.len());
        for (feat, _) in &active {
            eprintln!("  active: {feat}");
        }
        eprintln!("build.rs: available variants:");
        for (feat, _) in VARIANTS {
            eprintln!("  {feat}");
        }
        return Err(miette::miette!("expected at most one Redacted variant feature, found {}", active.len()));
    }

    let (feature, font_base) = if active.is_empty() { ("redacted", "Redacted-Regular") } else { *active[0] };
    let font_path = format!("{}/{font_base}.ttf", build_constants::RESOURCES_DIR);

    eprintln!("build.rs: active variant: {feature} -> {font_path}");

    // Set env var with absolute path so include_bytes! in fonts.rs can find it.
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| std::env::current_dir().unwrap().to_string_lossy().to_string());
    let absolute_font_path = Path::new(&crate_dir).join(&font_path);
    println!("cargo:rustc-env=REDACTED_FONT_PATH={}", absolute_font_path.display());

    let variant_slug = feature.replace('-', "_");
    let glyph_prefix = format!("redacted-{feature}");
    let gresource_prefix = format!("{}/redacted/{}", GRESOURCE_BASE_PREFIX, variant_slug);

    let config = ExportConfig {
        gresource_prefix: gresource_prefix.clone(),
        icons_context: "glyphs".to_string(),
        glyph_name_prefix: glyph_prefix.clone(),
        codepoint_ranges: &[(0x20, 0x7E)],
        axes: vec![],
    };

    FontBuild::new(&font_path)
        .extra_hash(feature)
        .run(|font_path, resources_dir| export_glyphs_with_config(font_path, resources_dir, &config))
        .map_err(|e| miette::miette!("{e}"))?;

    // Generate variant info (GRESOURCE_PREFIX, glyph prefix) for runtime use.
    let out_dir = std::env::var("OUT_DIR").into_diagnostic()?;
    let variant_info = format!(
        "// @generated by build.rs — do not edit\n\n\
         /// GResource prefix for the active Redacted variant.\n\
         pub const GRESOURCE_PREFIX: &str = \"{gresource_prefix}\";\n\n\
         /// Glyph name prefix for the active Redacted variant.\n\
         pub const GLYPH_PREFIX: &str = \"{glyph_prefix}\";\n"
    );
    std::fs::write(Path::new(&out_dir).join("variant.rs"), variant_info).into_diagnostic()?;

    Ok(())
}
