// build.rs: export Dicefont glyphs and generate codepoint maps + constants.
//
// Dicefont is a static icon font with die face glyphs for D2, D4, D6, D8,
// D10, D12, D20, and dot-d6 variants. All glyphs are in the Private Use
// Area (U+F100–U+F19B).

use std::path::Path;

use fonts_rs_generator::ExportConfig;
use fonts_rs_generator::FontBuild;
use fonts_rs_generator::build_constants;
use fonts_rs_generator::export_glyphs_with_config;
use fonts_rs_model::GRESOURCE_BASE_PREFIX;
use miette::IntoDiagnostic;

/// TTF font file name (relative to `resources/`).
pub const FONT_FILE: &str = "dicefont.ttf";

fn main() -> miette::Result<()> {
    let font_path = format!("{}/{}", build_constants::RESOURCES_DIR, FONT_FILE);

    eprintln!("build.rs: exporting glyphs from {font_path}");

    // Set env var with absolute path so include_bytes! in fonts.rs can find it.
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR")
        .unwrap_or_else(|_| std::env::current_dir().unwrap().to_string_lossy().to_string());
    let absolute_font_path = Path::new(&crate_dir).join(&font_path);
    println!("cargo:rustc-env=DICEFONT_FONT_PATH={}", absolute_font_path.display());

    let glyph_prefix = "dicefont";
    let gresource_prefix = format!("{}/dicefont", GRESOURCE_BASE_PREFIX);

    let config = ExportConfig {
        gresource_prefix: gresource_prefix.clone(),
        icons_context: "glyphs".to_string(),
        glyph_name_prefix: glyph_prefix.to_string(),
        codepoint_ranges: &[(0xF000, 0xFFFF)],
        axes: vec![],
        name_filter: None,
    };

    let icons_dir = Path::new(build_constants::RESOURCES_DIR)
        .join("scalable")
        .join("glyphs");

    FontBuild::new(&font_path)
        .run(|font_path, resources_dir| {
            if icons_dir.exists() {
                std::fs::remove_dir_all(&icons_dir)?;
            }
            export_glyphs_with_config(font_path, resources_dir, &config)
        })
        .map_err(|e| miette::miette!("{e}"))?;

    // Generate variant info for runtime use.
    let out_dir = std::env::var("OUT_DIR").into_diagnostic()?;
    let variant_info = format!(
        "// @generated by build.rs — do not edit\n\n\
         /// GResource prefix for Dicefont.\n\
         pub const GRESOURCE_PREFIX: &str = \"{gresource_prefix}\";\n\n\
         /// Glyph name prefix for Dicefont.\n\
         pub const GLYPH_PREFIX: &str = \"{glyph_prefix}\";\n"
    );
    std::fs::write(Path::new(&out_dir).join("variant.rs"), variant_info).into_diagnostic()?;

    Ok(())
}
