//! Generator for phf::Map codepoint lookup tables.

use std::path::PathBuf;

use super::IconEntry;
use super::error::GenerateError;
use super::generate::NerdFontsGenerator;

/// Generates phf::Map constants for both codepoint-to-name and name-to-codepoint lookups.
pub struct IconsCodemapGenerator;

impl NerdFontsGenerator for IconsCodemapGenerator {
    fn generate(icons: &[IconEntry]) -> Result<String, GenerateError> {
        let mut output = String::new();
        output.push_str("// @generated by build.rs — do not edit\n\n");
        output.push_str("use phf::phf_map;\n\n");

        // Codepoint -> name map
        output.push_str("pub static ICONS: phf::Map<char, &'static str> = phf_map! {\n");
        for icon in icons {
            let Some(code) = &icon.code else { continue };
            let ch = code.as_char();
            output.push_str(&format!("    '\\u{{{:X}}}' => \"{}\",\n", ch as u32, icon.name));
        }
        output.push_str("};\n\n");

        // Name -> codepoint map (reverse lookup)
        output.push_str("pub static REVERSE_ICONS: phf::Map<&'static str, char> = phf_map! {\n");
        for icon in icons {
            let Some(code) = &icon.code else { continue };
            let ch = code.as_char();
            output.push_str(&format!("    \"{}\" => '\\u{{{:X}}}',\n", icon.name, ch as u32));
        }
        output.push_str("};\n");

        Ok(output)
    }

    fn output_path() -> PathBuf {
        let out_dir = std::env::var("OUT_DIR").unwrap();
        PathBuf::from(out_dir).join("codemap.rs")
    }
}
