//! Generator for Rust icon name constants.

use std::collections::HashSet;
use std::path::PathBuf;

use super::error::GenerateError;
use super::generate::NerdFontsGenerator;
use nerd_fonts_model::GlyphEntry;
use nerd_fonts_model::IconName;

/// Generates Rust constants for each icon name.
pub struct IconsRustGenerator;

impl NerdFontsGenerator for IconsRustGenerator {
    fn generate(icons: &[GlyphEntry<IconName>]) -> Result<String, GenerateError> {
        let icons: HashSet<String> = icons.iter().map(|icon| icon.name.to_string()).collect();

        let mut output = String::new();
        output.push_str("// @generated by build.rs — do not edit\n\n");

        for icon in icons {
            let const_name = icon.to_uppercase().replace('-', "_");
            output.push_str(&format!("pub const {}: &str = \"{}\";\n", const_name, icon));
        }

        Ok(output)
    }

    fn output_path() -> Result<PathBuf, GenerateError> {
        let out_dir = std::env::var("OUT_DIR")?;
        Ok(PathBuf::from(out_dir).join("icons.rs"))
    }
}
