// build.rs: export DSEG14 glyphs and generate codepoint maps + constants.
//
// Detects the active Cargo feature (e.g. `classic-regular`, `modern-mini-bold`)
// and exports glyphs from the corresponding DSEG14 TTF variant.

use std::path::Path;

use fonts_rs_generator::FontBuild;
use fonts_rs_generator::ExportConfig;
use fonts_rs_generator::build_constants;
use fonts_rs_generator::export_glyphs_with_config;
use fonts_rs_model::GRESOURCE_BASE_PREFIX;
use miette::IntoDiagnostic;

/// All DSEG14 variants and their mapping to TTF filenames.
const VARIANTS: &[(&str, &str)] = &[
    // Classic
    ("classic-regular",          "DSEG14Classic-Regular"),
    ("classic-bold",             "DSEG14Classic-Bold"),
    ("classic-italic",           "DSEG14Classic-Italic"),
    ("classic-bold-italic",      "DSEG14Classic-BoldItalic"),
    ("classic-light",            "DSEG14Classic-Light"),
    ("classic-light-italic",     "DSEG14Classic-LightItalic"),
    // Classic Mini
    ("classic-mini-regular",     "DSEG14ClassicMini-Regular"),
    ("classic-mini-bold",        "DSEG14ClassicMini-Bold"),
    ("classic-mini-italic",      "DSEG14ClassicMini-Italic"),
    ("classic-mini-bold-italic", "DSEG14ClassicMini-BoldItalic"),
    ("classic-mini-light",       "DSEG14ClassicMini-Light"),
    ("classic-mini-light-italic","DSEG14ClassicMini-LightItalic"),
    // Modern
    ("modern-regular",           "DSEG14Modern-Regular"),
    ("modern-bold",              "DSEG14Modern-Bold"),
    ("modern-italic",            "DSEG14Modern-Italic"),
    ("modern-bold-italic",       "DSEG14Modern-BoldItalic"),
    ("modern-light",             "DSEG14Modern-Light"),
    ("modern-light-italic",      "DSEG14Modern-LightItalic"),
    // Modern Mini
    ("modern-mini-regular",      "DSEG14ModernMini-Regular"),
    ("modern-mini-bold",         "DSEG14ModernMini-Bold"),
    ("modern-mini-italic",       "DSEG14ModernMini-Italic"),
    ("modern-mini-bold-italic",  "DSEG14ModernMini-BoldItalic"),
    ("modern-mini-light",        "DSEG14ModernMini-Light"),
    ("modern-mini-light-italic", "DSEG14ModernMini-LightItalic"),
];

fn main() -> miette::Result<()> {
    let active = VARIANTS
        .iter()
        .filter(|(feat, _)| std::env::var(format!("CARGO_FEATURE_{}", feat.replace('-', "_").to_uppercase())).is_ok())
        .collect::<Vec<_>>();

    if active.is_empty() {
        eprintln!("build.rs: no DSEG14 variant feature active, defaulting to classic-regular");
    } else if active.len() > 1 {
        eprintln!("build.rs: expected at most one DSEG14 variant feature, found {active_len}", active_len = active.len());
        for (feat, _) in &active {
            eprintln!("  active: {feat}");
        }
        eprintln!("build.rs: available variants:");
        for (feat, _) in VARIANTS {
            eprintln!("  {feat}");
        }
        return Err(miette::miette!("expected at most one DSEG14 variant feature, found {}", active.len()));
    }

    let (feature, font_base) = if active.is_empty() {
        ("classic-regular", "DSEG14Classic-Regular")
    } else {
        *active[0]
    };
    let font_path = format!("{}/{font_base}.ttf", build_constants::RESOURCES_DIR);

    eprintln!("build.rs: active variant: {feature} -> {font_path}");

    // Set env var with absolute path so include_bytes! in fonts.rs can find it.
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR")
        .unwrap_or_else(|_| std::env::current_dir().unwrap().to_string_lossy().to_string());
    let absolute_font_path = Path::new(&crate_dir).join(&font_path);
    println!("cargo:rustc-env=DSEG14_FONT_PATH={}", absolute_font_path.display());

    let variant_slug = feature.replace('-', "_");
    let glyph_prefix = format!("dseg14-{feature}");
    let gresource_prefix = format!("{}/fourteen_segment/{}", GRESOURCE_BASE_PREFIX, variant_slug);

    let config = ExportConfig {
        gresource_prefix: gresource_prefix.clone(),
        icons_context: "glyphs".to_string(),
        glyph_name_prefix: glyph_prefix.clone(),
        codepoint_ranges: &[(0x20, 0x7E)],
    };

    FontBuild::new(&font_path)
        .run(|font_path, resources_dir| {
            export_glyphs_with_config(font_path, resources_dir, &config)
        })
        .map_err(|e| miette::miette!("{e}"))?;

    // Generate variant info (GRESOURCE_PREFIX, glyph prefix) for runtime use.
    let out_dir = std::env::var("OUT_DIR").into_diagnostic()?;
    let variant_info = format!(
        "// @generated by build.rs — do not edit\n\n\
         /// GResource prefix for the active DSEG14 variant.\n\
         pub const GRESOURCE_PREFIX: &str = \"{gresource_prefix}\";\n\n\
         /// Glyph name prefix for the active DSEG14 variant.\n\
         pub const GLYPH_PREFIX: &str = \"{glyph_prefix}\";\n"
    );
    std::fs::write(Path::new(&out_dir).join("variant.rs"), variant_info).into_diagnostic()?;

    Ok(())
}
