//! Generator for web CSS with per-icon content mappings.

use std::path::PathBuf;

use super::error::GenerateError;
use super::generate::NerdFontsGenerator;
use super::IconEntry;

/// Generates the web CSS file (`resources/nerdfont.css`) with per-icon
/// `content: "\XXXX"` mappings from metadata.json.
pub struct WebCssGenerator;

impl NerdFontsGenerator for WebCssGenerator {
    fn generate(icons: &[IconEntry]) -> Result<String, GenerateError> {
        let mut output = String::new();
        output.push_str("/* Nerd Font icon mappings for web instances.\n");
        output.push_str(" * Maps nf-* icon names to Unicode codepoints.\n");
        output.push_str(" * Generated from SymbolsNerdFont-Regular.ttf glyph table.\n");
        output.push_str(" * @generated by build.rs — do not edit\n");
        output.push_str(" */\n\n");

        output.push_str("@font-face {\n");
        output.push_str("    font-family: \"Symbols Nerd Font\";\n");
        output.push_str("    src: url(\"/static/nerdfont.woff2\") format(\"woff2\");\n");
        output.push_str("    font-weight: normal;\n");
        output.push_str("    font-style: normal;\n");
        output.push_str("    font-display: block;\n");
        output.push_str("}\n\n");

        output.push_str(".nerd-icon {\n");
        output.push_str("    font-family: \"Symbols Nerd Font\", monospace;\n");
        output.push_str("    display: inline-block;\n");
        output.push_str("    font-style: normal;\n");
        output.push_str("    font-weight: normal;\n");
        output.push_str("    line-height: 1;\n");
        output.push_str("}\n\n");

        let mut sorted: Vec<&IconEntry> = icons.iter().filter(|i| i.code.is_some()).collect();
        sorted.sort_by(|a, b| a.name.cmp(&b.name));

        for icon in sorted {
            let Some(code) = &icon.code else { continue };
            let ch = code.as_char();
            output.push_str(&format!(".nerd-{}:before {{\n    content: \"\\{:x}\"\n}}\n\n", icon.name, ch as u32));
        }

        Ok(output)
    }

    fn output_path() -> PathBuf {
        PathBuf::from("resources/nerdfont.css")
    }
}
