//! Generator for Noto Emoji metadata phf::Map tables (keywords and categories).
//!
//! Keywords are sourced from CLDR annotation data (`default` field).
//! Categories are sourced from Unicode `emoji-test.txt` (`group` field).

use std::collections::HashMap;
use std::path::PathBuf;

use fonts_rs_model::GlyphEntry;

/// Generates phf::Map constants for emoji keywords and categories.
///
/// Keywords come from CLDR annotation data. Categories come from
/// Unicode emoji-test.txt group headers.
pub struct NotoEmojiMetadataGenerator;

impl NotoEmojiMetadataGenerator {
    /// Generates the keywords phf::Map content.
    pub fn generate_keywords(entries: &[GlyphEntry<String>], keyword_map: &HashMap<u32, Vec<String>>) -> String {
        let mut output = String::new();
        output.push_str("// @generated by build.rs — do not edit\n\n");
        output.push_str("pub static KEYWORDS: GlyphKeywordMap = GlyphKeywordMap(phf::phf_map! {\n");

        for entry in entries {
            let glyph_name = &entry.name;
            let Some(code) = &entry.code else { continue };
            let cp = code.as_char() as u32;

            if let Some(kws) = keyword_map.get(&cp) {
                if !kws.is_empty() {
                    let kw_refs: Vec<String> = kws.iter().map(|k| format!("GlyphKeyword::new(\"{k}\")")).collect();
                    output.push_str(&format!("    \"{glyph_name}\" => &[{}],\n", kw_refs.join(", ")));
                }
            }
        }

        output.push_str("});\n");
        output
    }

    /// Generates the categories phf::Map content.
    pub fn generate_categories(entries: &[GlyphEntry<String>], category_map: &HashMap<u32, String>) -> String {
        let mut output = String::new();
        output.push_str("// @generated by build.rs — do not edit\n\n");
        output.push_str("pub static CATEGORIES: GlyphCategoryMap = GlyphCategoryMap(phf::phf_map! {\n");

        for entry in entries {
            let glyph_name = &entry.name;
            let Some(code) = &entry.code else { continue };
            let cp = code.as_char() as u32;

            if let Some(cat) = category_map.get(&cp) {
                output.push_str(&format!("    \"{glyph_name}\" => &[GlyphCategory::new(\"{cat}\")],\n"));
            }
        }

        output.push_str("});\n");
        output
    }

    /// Writes the generated metadata to separate output files.
    pub fn run(
        entries: &[GlyphEntry<String>],
        keyword_map: &HashMap<u32, Vec<String>>,
        category_map: &HashMap<u32, String>,
    ) -> Result<(), std::io::Error> {
        let out_dir = std::env::var("OUT_DIR").map_err(|e| std::io::Error::other(format!("OUT_DIR not set: {e}")))?;
        let out_dir = PathBuf::from(out_dir);
        std::fs::create_dir_all(&out_dir)?;

        let keywords = Self::generate_keywords(entries, keyword_map);
        std::fs::write(out_dir.join("keywords.rs"), keywords)?;

        let categories = Self::generate_categories(entries, category_map);
        std::fs::write(out_dir.join("categories.rs"), categories)?;

        Ok(())
    }
}
