// build.rs: export Chess Cuernavaca glyphs and generate codepoint maps + constants.
//
// Cuernavaca is a chess piece font where uppercase letters represent
// white pieces and lowercase letters represent black pieces.
// The font covers ASCII letters and a few punctuation marks.

use std::path::Path;

use fonts_rs_generator::ExportConfig;
use fonts_rs_generator::FontBuild;
use fonts_rs_generator::build_constants;
use fonts_rs_generator::export_glyphs_with_config;
use fonts_rs_model::ASCII_PRINTABLE_RANGE;
use fonts_rs_model::GRESOURCE_BASE_PREFIX;
use miette::IntoDiagnostic;

fn main() -> miette::Result<()> {
    let font_path = format!("{}/ChessCuernavaca.ttf", build_constants::RESOURCES_DIR);

    eprintln!("build.rs: exporting glyphs from {font_path}");

    // Set env var with absolute path so include_bytes! in fonts.rs can find it.
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| std::env::current_dir().unwrap().to_string_lossy().to_string());
    let absolute_font_path = Path::new(&crate_dir).join(&font_path);
    println!("cargo:rustc-env=CUERNAVACA_FONT_PATH={}", absolute_font_path.display());

    let glyph_prefix = "cuernavaca";
    let gresource_prefix = format!("{}/cuernavaca", GRESOURCE_BASE_PREFIX);

    let config = ExportConfig {
        gresource_prefix: gresource_prefix.clone(),
        icons_context: "glyphs".to_string(),
        glyph_name_prefix: glyph_prefix.to_string(),
        codepoint_ranges: ASCII_PRINTABLE_RANGE,
        axes: vec![],
        name_filter: None,
    };

    FontBuild::new(&font_path)
        .run(|font_path, resources_dir| export_glyphs_with_config(font_path, resources_dir, &config))
        .map_err(|e| miette::miette!("{e}"))?;

    // Generate variant info (GRESOURCE_PREFIX, glyph prefix) for runtime use.
    let out_dir = std::env::var("OUT_DIR").into_diagnostic()?;
    let variant_info = format!(
        "// @generated by build.rs — do not edit\n\n\
         /// GResource prefix for Cuernavaca glyphs.\n\
         pub const GRESOURCE_PREFIX: &str = \"{gresource_prefix}\";\n\n\
         /// Glyph name prefix for Cuernavaca glyphs.\n\
         pub const GLYPH_PREFIX: &str = \"{glyph_prefix}\";\n"
    );
    std::fs::write(Path::new(&out_dir).join("variant.rs"), variant_info).into_diagnostic()?;

    Ok(())
}
