name: MSRV
run-name: Minimum Supported Rust Version for ${{ github.ref == 'refs/heads/main' && 'Nightly' || github.event_name == 'pull_request' && format('{0} {1}', 'Pull Request', github.event.pull_request.number) || format('{0} {1}', 'Branch', github.ref) }} by @${{ github.actor }}

on:
  push:
    branches: [ main ]
    paths:
      - "crates/**/*.rs"
      - "crates/*/Cargo.toml"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/msrv.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "crates/**/*.rs"
      - "crates/*/Cargo.toml"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/msrv.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-26.04
    continue-on-error: true
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v7
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libgtk-4-dev libglib2.0-dev
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install cargo msrv
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: cargo-msrv@0.19.3
      - name: Version of cargo msrv
        run: cargo msrv --version
      - name: Verify MSRV (fonts-rs-model)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-model
      - name: Verify MSRV (fonts-rs-generator)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-generator
      - name: Verify MSRV (fonts-rs-seven-segment)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-seven-segment
      - name: Verify MSRV (fonts-rs-fourteen-segment)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-fourteen-segment
      - name: Verify MSRV (fonts-rs-barcode-code39)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-barcode-code39
      - name: Verify MSRV (fonts-rs-barcode-code128)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-barcode-code128
      - name: Verify MSRV (fonts-rs-barcode-ean13)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-barcode-ean13
      - name: Verify MSRV (fonts-rs-doto)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-doto
      - name: Verify MSRV (fonts-rs-redacted)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-redacted
      - name: Verify MSRV (fonts-rs-dicefont)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-dicefont
      - name: Verify MSRV (fonts-rs-bravura)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-bravura
      - name: Verify MSRV (fonts-rs-cuernavaca)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-cuernavaca
      - name: Verify MSRV (fonts-rs-noto-emoji)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-noto-emoji
      - name: Verify MSRV (fonts-rs-noto-emoji-generator)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-noto-emoji-generator
      - name: Verify MSRV (fonts-rs-noto-emoji-cheat-sheet)
        run: cargo msrv --output-format json verify --path crates/fonts-rs-noto-emoji-cheat-sheet
      - name: Verify MSRV (nerd-fonts-model)
        run: cargo msrv --output-format json verify --path crates/nerd-fonts-model
      - name: Verify MSRV (nerd-fonts-generator)
        run: cargo msrv --output-format json verify --path crates/nerd-fonts-generator
      - name: Verify MSRV (nerd-fonts-rs)
        run: cargo msrv --output-format json verify --path crates/nerd-fonts-rs
      - name: Verify MSRV (nerd-fonts-cheat-sheet)
        run: cargo msrv --output-format json verify --path crates/nerd-fonts-cheat-sheet
      - name: Find MSRV on verify failure
        if: ${{ failure() }}
        run: cargo msrv --output-format json find --path crates/fonts-rs-model || true
